name: screen_scene
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.0.2
  cloud_firestore: ^5.5.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.5
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  google_sign_in:
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Regular.ttf
        weight: 400
      - asset: assets/fonts/Cairo-Medium.ttf
        weight: 500
      - asset: assets/fonts/Cairo-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 700
